### ISSUE TITLE
index all daily logs and supply search service

### ISSUE THREAD

**Issue by xlongwei** [jdrews/logstation#31]
index all daily logs
1, old logs
2, old logs compressed in gz
3, current logs, update automatically

search service, support line parse: 
1, line is a whole string, optional equals to : {"line":"log line"}
2, line => json, ex: {"ip":"address","msg":"message","level":"INFO"}
sometimes line parse is difficult, so option 1 is good enough

**Comment by jdrews** [comment]
There are tools that rotate logs for you. On check out [logrotate](https://linux.die.net/man/8/logrotate) or [logrotatewin](https://github.com/plecos/logrotatewin)

Search is probably out of scope of this project. I'd checkout graylog, splunk, or ELK (Elasticsearch, Logstash, Kibana).
