### ISSUE TITLE
logstation does not seem to respect "-c" argument

### ISSUE THREAD

**Issue by Kkevsterrr** [jdrews/logstation#34]
I tried using logstation -c, but it does not seem to respect it. 

```
$ mv logstation.conf logstation_othername.conf
$ java -jar logstation-0.3.10.jar -c logstation_othername.conf 
Welcome to logstation! Creating default logstation.conf...
Please setup your logstation.conf located here: /home/kbock/tincture3/logstation.conf
Then relaunch and logstation will be located at: http://127.0.0.1:0
```
Am I passing the flags incorrectly? Thanks for your help!

**Comment by jdrews** [comment]
That looks right to me. 

Can you tell me more about your environment? What OS, and java versions? Thanks!

**Comment by Kkevsterrr** [comment]
Sure thing! I'm running in a Linux Ubuntu 16.04 VM. 
```
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by jdrews** [comment]
Ok cool. I'll spin up a Ubuntu 16.04 VM here in a sec and try it out.

**Comment by Kkevsterrr** [comment]
Thanks so much!!

**Comment by jdrews** [comment]
Does it have a desktop environment? Or are you running it with no desktop environment?

**Comment by Kkevsterrr** [comment]
There is a desktop environment, but I would ideally like to run this headlessly, and be able to access the logs from another machine. (Run logstation on a server with logs, see those logs on other computers)

**Comment by jdrews** [comment]
Ok makes sense. I haven't tried it headless before. I'll give it a go and see what happens.

**Comment by jdrews** [comment]
I was able to recreate the problem with it not honoring the `-c` parameter. Looking into it.

**Comment by Kkevsterrr** [comment]
Sweet - I'll give it a shot. Does the pre-release address both #34 and #33, or just #34?

**Comment by Kkevsterrr** [comment]
`[INFO] [10/12/2018 21:36:47.458] [main] [LogStation$] Unable to launch browser automatically.` works like a charm :)

**Comment by jdrews** [comment]
Both

**Comment by Kkevsterrr** [comment]
Tested #33 as well and it works great. Thanks so much for your fast response on this! I'll keep playing with it as I work to integrate it and let you know if I run into anything else.

**Comment by Kkevsterrr** [comment]
(I'll let you close these issues when you want to; you're free to close them now if you want, or you can do it when the pre-release is a full release)

**Comment by jdrews** [comment]
Glad it's working. I'll close out the issues.
