### ISSUE TITLE
Logstation stops working after refresh

### ISSUE THREAD

**Issue by Kkevsterrr** [jdrews/logstation#35]
It's unclear to me why this is, and it seems to affect 3.10 and 3.11. If you get logstation open and are tailing files, if you refresh the page for any reason, logstation stops working - no files show up to be tailed.

**Comment by jdrews** [comment]
When you refresh the page, the client waits for new log lines to show. I suspect the logs hadn't updated with any new log files. 

Please feel free to comment if I'm incorrectly diagnosing your problem. Thanks for stopping by!

**Comment by jdrews** [comment]
Possibly related to https://github.com/jdrews/logstation/issues/42?
