### ISSUE TITLE
Is Authentication available?

### ISSUE THREAD

**Issue by reddysainathn** [jdrews/logstation#37]
Hello,

The app is really cool, which could help me a lot.Just wanted to check if authentication is available.

**Comment by vaLski** [comment]
@reddysainathnmake the app listening on 127.0.0.1:port

**Comment by vaLski** [comment]
I would do the following:

* Make application listening on 127.0.0.1:port_of_your_choice
* Make nginx + ssl listening on https://server.com/endpoint
* Make nginx forward traffic to that endpoint to https://github.com/bitly/oauth2_proxy
* Forward authenticated oauth2 requests to your app 127.0.0.1:port_of_your_choice

There you go.

**Comment by jdrews** [comment]
Good idea but probably out of scope for this tool. I agree with @vaLski's comment. Thanks!
