### ISSUE TITLE
Connections get dropped

### ISSUE THREAD

**Issue by sieglej** [jdrews/logstation#42]
It looks like connections get dropped or stop getting updated.  I see "Received shutdown" and "session expired" messaged for threads and don't know if those are the related connections.  
Also after refreshing the browser, no additional updates are received (clearing the cookie in Chrome will sometimes allow updates to continue).  I'm running on CentOS6.10, java 1.7.0_67

**Comment by jdrews** [comment]
I wasn't able to reproduce this. If you have more steps to reproduce I'd definitely like to hear it. Closing ticket for now.
