### ISSUE TITLE
binding to 0.0.0.0 issue

### ISSUE THREAD

**Issue by pgy1pgy1** [jdrews/logstation#43]
When running the application, service binds to all interfaces by default. That is, it binds to 0.0.0.0 on the specified port.
From a security perspective, this is not desirable. The default behavior of any service should be to bind only to the localhost (127.0.0.1) interface by default, and allow overriding the bind address via config file.

**Comment by jdrews** [comment]
My plan is to add the ability to configure the bind address in the conf file.

**Comment by jdrews** [comment]
Resolved in upcoming release of 2.0
