### ISSUE TITLE
Wildcards or directories?

### ISSUE THREAD

**Issue by jasdjensen** [jdrews/logstation#44]
This is a life saver.  I love it! Thank you.  I'm wondering how difficult it would be to add a list of files from the directory so we caught pick which one to view?  My log files change each day, so it would be great not to have to reset this every day.  Maybe with a wildcard filter like *.log or *.txt?

**Comment by jdrews** [comment]
Probably listing files on the server to pick is out of scope.

However it makes sense to have the system monitor files via wildcard in the use case where your files rotate by date or file size. Adding to roadmap of next release.

**Comment by jdrews** [comment]
Resolved in https://github.com/jdrews/logstation/commit/8a612b5983fed860c0f72b09822f31beb51365b3. Release of 2.0 coming soon with this capability.
